# Generated by Django 5.0.4 on 2024-04-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="owner_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="customers.customer"
            ),
        ),
        migrations.AddField(
            model_name="historicaccountbalance",
            name="account_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.account"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(models.F("owner_id"), name="Index accounts by owner id"),
        ),
        migrations.AddIndex(
            model_name="historicaccountbalance",
            index=models.Index(
                fields=["account_id", "for_date"], name="Index of account balances"
            ),
        ),
        migrations.AddConstraint(
            model_name="historicaccountbalance",
            constraint=models.UniqueConstraint(
                fields=("account_id", "for_date"),
                name="Unique account balance for date",
            ),
        ),
    ]
