# Generated by Django 5.0.4 on 2024-04-22 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("currencies", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.TextField(
                        choices=[("REFILL", "Refill"), ("SPENDING", "Spending")],
                        default="SPENDING",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.account",
                    ),
                ),
                (
                    "currency_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="currencies.currency",
                    ),
                ),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["customer_id"], name="customer_id_index"),
                    models.Index(fields=["account_id"], name="account_id_index"),
                ],
            },
        ),
    ]
