# Generated by Django 5.0.4 on 2024-04-22 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("first_name", models.CharField()),
                ("last_name", models.CharField()),
                ("gender", models.CharField(choices=[("M", "Male"), ("F", "Female")])),
                ("birth_date", models.DateField()),
                ("address", models.TextField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name", "birth_date"), name="Unique_customer"
            ),
        ),
    ]
